'use strict';

const voladuras = [
  {
    voladuraId: 1,
    nombre: 'X967',
    anio: 2019,
    tipoVoladuraId: 5,
    comentario: 'Pendiente Revisión de Perfiles de Cargue',
    nivel: 'N+085',
    tipoCota: 'Superficie',
    gridPiso: 'X+085-1',
    tienePrecorte: true,
    panel: 116,
    pala: 'E24',
    manto: 145,
    patron: '7.4x9.30',
    alturaBanco: 12
  },
  {
    voladuraId: 2,
    nombre: 'S588',
    anio: 2019,
    tipoVoladuraId: 2,
    comentario: 'Pendiente definición de cargue especial',
    nivel: 'N-035',
    tipoCota: 'Superficie',
    gridPiso: 'S-035-1',
    tienePrecorte: false,
    panel: 20,
    pala: 'E24',
    manto: 180,
    patron: '7.0x8.58',
    alturaBanco: 11
  },
  {
    voladuraId: 3,
    nombre: 'F897',
    anio: 2019,
    tipoVoladuraId: 4,
    comentario: 'Area en mal estado. Sin random',
    nivel: 'N-045',
    tipoCota: 'Superficie',
    gridPiso: 'F-045-1',
    tienePrecorte: true,
    panel: 15,
    pala: 'E25',
    manto: 75,
    patron: '7.0x8.58',
    alturaBanco: 12
  },
  {
    voladuraId: 4,
    nombre: 'O936',
    anio: 2020,
    tipoVoladuraId: 4,
    comentario: 'Confirmar Cambio de Footwall',
    nivel: 'N-035',
    tipoCota: 'Superficie',
    gridPiso: 'O-035-1',
    tienePrecorte: false,
    panel: 110,
    pala: 'E24',
    manto: 75,
    patron: '7.4x9.30',
    alturaBanco: 12
  },
  {
    voladuraId: 5,
    nombre: 'F493',
    anio: 2019,
    tipoVoladuraId: 5,
    comentario: 'Sin estructuras',
    nivel: 'N-045',
    tipoCota: 'Superficie',
    gridPiso: 'F-045-1',
    tienePrecorte: true,
    panel: 22,
    pala: 'Q05',
    manto: 75,
    patron: '7.4x9.30',
    alturaBanco: 11
  },
  {
    voladuraId: 6,
    nombre: 'F335',
    anio: 2019,
    tipoVoladuraId: 3,
    comentario: 'Confirmar si se garantiza la cabeza del manto',
    nivel: 'N+120',
    tipoCota: 'Superficie',
    gridPiso: 'F+120-1',
    tienePrecorte: false,
    panel: 116,
    pala: 'E26',
    manto: 180,
    patron: '6.4x7.39',
    alturaBanco: 11
  },
  {
    voladuraId: 7,
    nombre: 'O210',
    anio: 2019,
    tipoVoladuraId: 5,
    comentario: 'Confirmar si se necesita nuevo polígono',
    nivel: 'N+000',
    tipoCota: 'Cota Plana',
    gridPiso: '',
    tienePrecorte: false,
    panel: 15,
    pala: 'Q05',
    manto: 180,
    patron: '7.0x8.58',
    alturaBanco: 11
  },
  {
    voladuraId: 8,
    nombre: 'M256',
    anio: 2019,
    tipoVoladuraId: 5,
    comentario: 'Confirmar datos con planeación',
    nivel: 'N-035',
    tipoCota: 'Cota Plana',
    gridPiso: '',
    tienePrecorte: false,
    panel: 110,
    pala: 'E26',
    manto: 180,
    patron: '7.0x8.58',
    alturaBanco: '10.5'
  },
  {
    voladuraId: 9,
    nombre: 'W928',
    anio: 2019,
    tipoVoladuraId: 1,
    comentario: 'Pendiente levantar pata del talud',
    nivel: 'N-035',
    tipoCota: 'Superficie',
    gridPiso: 'W-035-1',
    tienePrecorte: false,
    panel: 85,
    pala: 'I15',
    manto: 55,
    patron: '6.4x7.39',
    alturaBanco: 11
  },
  {
    voladuraId: 10,
    nombre: 'E252',
    anio: 2019,
    tipoVoladuraId: 4,
    comentario: 'Definir manto objetivo',
    nivel: 'N+000',
    tipoCota: 'Cota Plana',
    gridPiso: '',
    tienePrecorte: false,
    panel: 116,
    pala: 'E22',
    manto: 55,
    patron: '6.4x7.39',
    alturaBanco: 11
  },
  {
    voladuraId: 11,
    nombre: 'W816',
    anio: 2020,
    tipoVoladuraId: 6,
    comentario: 'Pendiente definición de corredor sur',
    nivel: 'N+060',
    tipoCota: 'Cota Plana',
    gridPiso: '',
    tienePrecorte: false,
    panel: 20,
    pala: 'E26',
    manto: 145,
    patron: '7.0x8.58',
    alturaBanco: 11
  },
  {
    voladuraId: 12,
    nombre: 'E881',
    anio: 2020,
    tipoVoladuraId: 2,
    comentario: 'Pendiente Revisión de Perfiles de Cargue',
    nivel: 'N+000',
    tipoCota: 'Superficie',
    gridPiso: 'E+000-1',
    tienePrecorte: false,
    panel: 15,
    pala: 'E26',
    manto: 50,
    patron: '7.4x9.30',
    alturaBanco: 12
  },
  {
    voladuraId: 13,
    nombre: 'E512',
    anio: 2020,
    tipoVoladuraId: 1,
    comentario: 'Pendiente Revisión de Perfiles de Cargue',
    nivel: 'N-035',
    tipoCota: 'Cota Plana',
    gridPiso: '',
    tienePrecorte: false,
    panel: 22,
    pala: 'Q05',
    manto: 102,
    patron: '7.4x9.30',
    alturaBanco: '10.5'
  },
  {
    voladuraId: 14,
    nombre: 'X027',
    anio: 2020,
    tipoVoladuraId: 5,
    comentario: 'Material acumulado al norte',
    nivel: 'N+085',
    tipoCota: 'Superficie',
    gridPiso: 'X+085-1',
    tienePrecorte: false,
    panel: 110,
    pala: 'E21',
    manto: 102,
    patron: '7.0x8.58',
    alturaBanco: 11
  },
  {
    voladuraId: 15,
    nombre: 'N468',
    anio: 2020,
    tipoVoladuraId: 2,
    comentario: 'Confirmar deckings en la parte superior',
    nivel: 'N-035',
    tipoCota: 'Superficie',
    gridPiso: 'N-035-1',
    tienePrecorte: false,
    panel: 22,
    pala: 'E21',
    manto: 102,
    patron: '7.4x9.30',
    alturaBanco: 11
  },
  {
    voladuraId: 16,
    nombre: 'P303',
    anio: 2019,
    tipoVoladuraId: 2,
    comentario: 'Falta limpieza del sur del footwall',
    nivel: 'N+060',
    tipoCota: 'Cota Plana',
    gridPiso: '',
    tienePrecorte: false,
    panel: 20,
    pala: 'Q05',
    manto: 105,
    patron: '7.0x8.58',
    alturaBanco: 12
  },
  {
    voladuraId: 17,
    nombre: 'E088',
    anio: 2019,
    tipoVoladuraId: 4,
    comentario: 'Falta limpieza del sur del footwall',
    nivel: 'N-045',
    tipoCota: 'Cota Plana',
    gridPiso: '',
    tienePrecorte: true,
    panel: 22,
    pala: 'E26',
    manto: 150,
    patron: '6.4x7.39',
    alturaBanco: 10
  },
  {
    voladuraId: 18,
    nombre: 'F589',
    anio: 2019,
    tipoVoladuraId: 1,
    comentario: 'Falta definición del plan de taladro',
    nivel: 'N+060',
    tipoCota: 'Superficie',
    gridPiso: 'F+060-1',
    tienePrecorte: false,
    panel: 22,
    pala: 'E23',
    manto: 60,
    patron: '7.0x8.58',
    alturaBanco: 11
  },
  {
    voladuraId: 19,
    nombre: 'W523',
    anio: 2020,
    tipoVoladuraId: 5,
    comentario: 'Confirmar autorización de entrega',
    nivel: 'N+060',
    tipoCota: 'Superficie',
    gridPiso: 'W+060-1',
    tienePrecorte: false,
    panel: 17,
    pala: 'I15',
    manto: 100,
    patron: '7.0x8.58',
    alturaBanco: 11
  },
  {
    voladuraId: 20,
    nombre: 'X438',
    anio: 2019,
    tipoVoladuraId: 5,
    comentario: 'Pendiente revisión de pared norte',
    nivel: 'N+085',
    tipoCota: 'Superficie',
    gridPiso: 'X+085-1',
    tienePrecorte: false,
    panel: 9,
    pala: 'E26',
    manto: 75,
    patron: '7.4x9.30',
    alturaBanco: 10
  },
  {
    voladuraId: 21,
    nombre: 'A050',
    anio: 2019,
    tipoVoladuraId: 4,
    comentario: 'Pendiente definición de cargue especial',
    nivel: 'N+085',
    tipoCota: 'Cota Plana',
    gridPiso: '',
    tienePrecorte: false,
    panel: 17,
    pala: 'E24',
    manto: 55,
    patron: '6.4x7.39',
    alturaBanco: 12
  },
  {
    voladuraId: 22,
    nombre: 'P822',
    anio: 2019,
    tipoVoladuraId: 4,
    comentario: 'Pendiente Conciliación de la pared',
    nivel: 'N+085',
    tipoCota: 'Cota Plana',
    gridPiso: '',
    tienePrecorte: false,
    panel: 116,
    pala: 'E21',
    manto: 150,
    patron: '7.4x9.30',
    alturaBanco: 11
  },
  {
    voladuraId: 23,
    nombre: 'F277',
    anio: 2020,
    tipoVoladuraId: 4,
    comentario: 'Se requiere rediseño',
    nivel: 'N+120',
    tipoCota: 'Cota Plana',
    gridPiso: '',
    tienePrecorte: false,
    panel: 116,
    pala: 'E23',
    manto: 55,
    patron: '7.4x9.30',
    alturaBanco: 11
  },
  {
    voladuraId: 24,
    nombre: 'N803',
    anio: 2019,
    tipoVoladuraId: 6,
    comentario: 'Falta limpieza del sur del footwall',
    nivel: 'N-045',
    tipoCota: 'Superficie',
    gridPiso: 'N-045-1',
    tienePrecorte: false,
    panel: 116,
    pala: 'E25',
    manto: 105,
    patron: '7.0x8.58',
    alturaBanco: 11
  },
  {
    voladuraId: 25,
    nombre: 'P805',
    anio: 2020,
    tipoVoladuraId: 2,
    comentario: 'Falta Limite de mineria del planeador',
    nivel: 'N+000',
    tipoCota: 'Superficie',
    gridPiso: 'P+000-1',
    tienePrecorte: false,
    panel: 9,
    pala: 'E26',
    manto: 180,
    patron: '7.4x9.30',
    alturaBanco: 11
  },
  {
    voladuraId: 26,
    nombre: 'P546',
    anio: 2019,
    tipoVoladuraId: 3,
    comentario: 'Definir utilización de globos',
    nivel: 'N-045',
    tipoCota: 'Superficie',
    gridPiso: 'P-045-1',
    tienePrecorte: false,
    panel: 110,
    pala: 'K02',
    manto: 60,
    patron: '7.0x8.58',
    alturaBanco: '10.5'
  },
  {
    voladuraId: 27,
    nombre: 'N480',
    anio: 2020,
    tipoVoladuraId: 5,
    comentario: 'Confirmar presencia de arenisca',
    nivel: 'N+000',
    tipoCota: 'Superficie',
    gridPiso: 'N+000-1',
    tienePrecorte: false,
    panel: 9,
    pala: 'Q05',
    manto: 50,
    patron: '6.4x7.39',
    alturaBanco: '10.5'
  },
  {
    voladuraId: 28,
    nombre: 'X792',
    anio: 2020,
    tipoVoladuraId: 3,
    comentario: 'Pendiente Revisión de Perfiles de Cargue',
    nivel: 'N+085',
    tipoCota: 'Superficie',
    gridPiso: 'X+085-1',
    tienePrecorte: false,
    panel: 110,
    pala: 'Q06',
    manto: 180,
    patron: '7.0x8.58',
    alturaBanco: 11
  },
  {
    voladuraId: 29,
    nombre: 'M595',
    anio: 2019,
    tipoVoladuraId: 5,
    comentario: 'Revisar ampliación del patrón',
    nivel: 'N+060',
    tipoCota: 'Superficie',
    gridPiso: 'M+060-1',
    tienePrecorte: false,
    panel: 9,
    pala: 'I16',
    manto: 50,
    patron: '7.0x8.58',
    alturaBanco: 11
  },
  {
    voladuraId: 30,
    nombre: 'E852',
    anio: 2019,
    tipoVoladuraId: 1,
    comentario: 'Confirmar autorización de entrega',
    nivel: 'N+060',
    tipoCota: 'Superficie',
    gridPiso: 'E+060-1',
    tienePrecorte: false,
    panel: 115,
    pala: 'Q06',
    manto: 75,
    patron: '6.4x7.39',
    alturaBanco: '10.5'
  },
  {
    voladuraId: 31,
    nombre: 'N600',
    anio: 2019,

    tipoVoladuraId: 6,
    comentario: 'Pendiente Revisión de Perfiles de Cargue',
    nivel: 'N-045',
    tipoCota: 'Cota Plana',
    gridPiso: '',
    tienePrecorte: false,
    panel: 20,
    pala: 'K02',
    manto: 102,
    patron: '6.4x7.39',
    alturaBanco: '10.5'
  },
  {
    voladuraId: 32,
    nombre: 'A284',
    anio: 2020,
    tipoVoladuraId: 1,
    comentario: 'Falta Limite de mineria del planeador',
    nivel: 'N-045',
    tipoCota: 'Cota Plana',
    gridPiso: '',
    tienePrecorte: false,
    panel: 116,
    pala: 'E23',
    manto: 105,
    patron: '7.0x8.58',
    alturaBanco: '10.5'
  },
  {
    voladuraId: 33,
    nombre: 'F344',
    anio: 2019,
    tipoVoladuraId: 5,
    comentario: 'Confirmar deckings en la parte superior',
    nivel: 'N+085',
    tipoCota: 'Cota Plana',
    gridPiso: '',
    tienePrecorte: false,
    panel: 116,
    pala: 'Q05',
    manto: 100,
    patron: '7.0x8.58',
    alturaBanco: 10
  },
  {
    voladuraId: 34,
    nombre: 'O827',
    anio: 2020,
    tipoVoladuraId: 6,
    comentario: 'Pendiente levantar pata del talud',
    nivel: 'N+085',
    tipoCota: 'Superficie',
    gridPiso: 'O+085-1',
    tienePrecorte: true,
    panel: 17,
    pala: 'Q06',
    manto: 75,
    patron: '7.0x8.58',
    alturaBanco: 11
  },
  {
    voladuraId: 35,
    nombre: 'S985',
    anio: 2020,
    tipoVoladuraId: 5,
    comentario: 'Confirmar datos con planeación',
    nivel: 'N-035',
    tipoCota: 'Superficie',
    gridPiso: 'S-035-1',
    tienePrecorte: true,
    panel: 110,
    pala: 'I16',
    manto: 145,
    patron: '7.0x8.58',
    alturaBanco: 10
  },
  {
    voladuraId: 36,
    nombre: 'N794',
    anio: 2019,
    tipoVoladuraId: 6,
    comentario: 'Area en mal estado. Sin random',
    nivel: 'N-045',
    tipoCota: 'Superficie',
    gridPiso: 'N-045-1',
    tienePrecorte: false,
    panel: 85,
    pala: 'K01',
    manto: 100,
    patron: '6.4x7.39',
    alturaBanco: 10
  },
  {
    voladuraId: 37,
    nombre: 'S856',
    anio: 2019,
    tipoVoladuraId: 1,
    comentario: 'Falta Formato de entrega de Area',
    nivel: 'N+060',
    tipoCota: 'Superficie',
    gridPiso: 'S+060-1',
    tienePrecorte: false,
    panel: 22,
    pala: 'E21',
    manto: 102,
    patron: '7.0x8.58',
    alturaBanco: 11
  },
  {
    voladuraId: 38,
    nombre: 'X506',
    anio: 2020,
    tipoVoladuraId: 5,
    comentario: 'Pendiente revisión de pared norte',
    nivel: 'N+120',
    tipoCota: 'Superficie',
    gridPiso: 'X+120-1',
    tienePrecorte: false,
    panel: 116,
    pala: 'Q06',
    manto: 55,
    patron: '6.4x7.39',
    alturaBanco: 11
  },
  {
    voladuraId: 39,
    nombre: 'N011',
    anio: 2019,
    tipoVoladuraId: 6,
    comentario: 'Confirmar deckings en la parte superior',
    nivel: 'N+000',
    tipoCota: 'Superficie',
    gridPiso: 'N+000-1',
    tienePrecorte: false,
    panel: 20,
    pala: 'I15',
    manto: 100,
    patron: '7.0x8.58',
    alturaBanco: 10
  },
  {
    voladuraId: 40,
    nombre: 'O569',
    anio: 2019,
    tipoVoladuraId: 3,
    comentario: 'Pendiente Revisión de Perfiles de Cargue',
    nivel: 'N-045',
    tipoCota: 'Superficie',
    gridPiso: 'O-045-1',
    tienePrecorte: false,
    panel: 115,
    pala: 'E24',
    manto: 150,
    patron: '6.4x7.39',
    alturaBanco: 12
  },
  {
    voladuraId: 41,
    nombre: 'S926',
    anio: 2020,
    tipoVoladuraId: 1,
    comentario: 'Confirmar en turno nocturno para entrega',
    nivel: 'N+085',
    tipoCota: 'Superficie',
    gridPiso: 'S+085-1',
    tienePrecorte: false,
    panel: 9,
    pala: 'Q06',
    manto: 105,
    patron: '7.4x9.30',
    alturaBanco: 11
  },
  {
    voladuraId: 42,
    nombre: 'O159',
    anio: 2020,
    tipoVoladuraId: 2,
    comentario: 'Pendiente definición de cargue especial',
    nivel: 'N-045',
    tipoCota: 'Superficie',
    gridPiso: 'O-045-1',
    tienePrecorte: false,
    panel: 9,
    pala: 'I16',
    manto: 180,
    patron: '6.4x7.39',
    alturaBanco: 12
  },
  {
    voladuraId: 43,
    nombre: 'N856',
    anio: 2020,
    tipoVoladuraId: 5,
    comentario: 'Pendiente definición de cargue especial',
    nivel: 'N+000',
    tipoCota: 'Superficie',
    gridPiso: 'N+000-1',
    tienePrecorte: true,
    panel: 15,
    pala: 'I15',
    manto: 105,
    patron: '7.0x8.58',
    alturaBanco: '10.5'
  },
  {
    voladuraId: 44,
    nombre: 'O334',
    anio: 2019,
    tipoVoladuraId: 6,
    comentario: 'Confirmar presencia de arenisca',
    nivel: 'N+060',
    tipoCota: 'Superficie',
    gridPiso: 'O+060-1',
    tienePrecorte: false,
    panel: 85,
    pala: 'Q05',
    manto: 102,
    patron: '7.0x8.58',
    alturaBanco: 12
  },
  {
    voladuraId: 45,
    nombre: 'S690',
    anio: 2020,
    tipoVoladuraId: 1,
    comentario: 'Se requiere rediseño',
    nivel: 'N+060',
    tipoCota: 'Superficie',
    gridPiso: 'S+060-1',
    tienePrecorte: false,
    panel: 22,
    pala: 'E24',
    manto: 105,
    patron: '7.0x8.58',
    alturaBanco: 11
  },
  {
    voladuraId: 46,
    nombre: 'P071',
    anio: 2020,
    tipoVoladuraId: 5,
    comentario: 'Pendiente Revisión de Perfiles de Cargue',
    nivel: 'N-045',
    tipoCota: 'Cota Plana',
    gridPiso: '',
    tienePrecorte: false,
    panel: 116,
    pala: 'E22',
    manto: 150,
    patron: '6.4x7.39',
    alturaBanco: 10
  },
  {
    voladuraId: 47,
    nombre: 'F499',
    anio: 2020,
    tipoVoladuraId: 4,
    comentario: 'Confirmar si se necesita nuevo polígono',
    nivel: 'N-035',
    tipoCota: 'Superficie',
    gridPiso: 'F-035-1',
    tienePrecorte: false,
    panel: 115,
    pala: 'Q06',
    manto: 55,
    patron: '7.4x9.30',
    alturaBanco: 11
  },
  {
    voladuraId: 48,
    nombre: 'X681',
    anio: 2019,
    tipoVoladuraId: 5,
    comentario: 'Confirmar en turno nocturno para entrega',
    nivel: 'N-035',
    tipoCota: 'Superficie',
    gridPiso: 'X-035-1',
    tienePrecorte: false,
    panel: 20,
    pala: 'I16',
    manto: 150,
    patron: '7.0x8.58',
    alturaBanco: 12
  },
  {
    voladuraId: 49,
    nombre: 'N034',
    anio: 2020,
    tipoVoladuraId: 4,
    comentario: 'Revisar ampliación del patrón',
    nivel: 'N+000',
    tipoCota: 'Superficie',
    gridPiso: 'N+000-1',
    tienePrecorte: false,
    panel: 85,
    pala: 'I15',
    manto: 105,
    patron: '7.0x8.58',
    alturaBanco: 12
  },
  {
    voladuraId: 50,
    nombre: 'N897',
    anio: 2020,
    tipoVoladuraId: 4,
    comentario: 'Falta Formato de entrega de Area',
    nivel: 'N+000',
    tipoCota: 'Superficie',
    gridPiso: 'N+000-1',
    tienePrecorte: false,
    panel: 116,
    pala: 'I16',
    manto: 105,
    patron: '7.4x9.30',
    alturaBanco: 11
  }
];

const normalizedVols = voladuras.map((voladura) => {
  return {
    ...voladura,
    panel: `${voladura.panel}`,
    manto: `${voladura.manto}`,
    alturaBanco: parseFloat(voladura.alturaBanco)
  };
});

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('voladuras', normalizedVols, {});
  },

  down: (queryInterface, Sequelize) => {
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.bulkDelete('People', null, {});
    */
  }
};
